from __future__ import annotations

# Static Nifty-class map so Phase 1 allocation visuals are honest.
# Screener.in will replace this in Phase 3.

UNIVERSE: dict[str, dict[str, str]] = {
    "RELIANCE": {"name": "Reliance Industries", "sector": "Energy", "mcap": "Large"},
    "TCS": {"name": "Tata Consultancy Services", "sector": "Information Technology", "mcap": "Large"},
    "HDFCBANK": {"name": "HDFC Bank", "sector": "Financials", "mcap": "Large"},
    "ICICIBANK": {"name": "ICICI Bank", "sector": "Financials", "mcap": "Large"},
    "INFY": {"name": "Infosys", "sector": "Information Technology", "mcap": "Large"},
    "ITC": {"name": "ITC", "sector": "FMCG", "mcap": "Large"},
    "BHARTIARTL": {"name": "Bharti Airtel", "sector": "Telecom", "mcap": "Large"},
    "SBIN": {"name": "State Bank of India", "sector": "Financials", "mcap": "Large"},
    "LT": {"name": "Larsen & Toubro", "sector": "Industrials", "mcap": "Large"},
    "ASIANPAINT": {"name": "Asian Paints", "sector": "Materials", "mcap": "Large"},
    "MARUTI": {"name": "Maruti Suzuki", "sector": "Automobile", "mcap": "Large"},
    "SUNPHARMA": {"name": "Sun Pharmaceutical", "sector": "Healthcare", "mcap": "Large"},
    "TITAN": {"name": "Titan Company", "sector": "Consumer Discretionary", "mcap": "Large"},
    "ULTRACEMCO": {"name": "UltraTech Cement", "sector": "Materials", "mcap": "Large"},
    "NESTLEIND": {"name": "Nestlé India", "sector": "FMCG", "mcap": "Large"},
    "BAJFINANCE": {"name": "Bajaj Finance", "sector": "Financials", "mcap": "Large"},
    "BAJAJFINSV": {"name": "Bajaj Finserv", "sector": "Financials", "mcap": "Large"},
    "HINDUNILVR": {"name": "Hindustan Unilever", "sector": "FMCG", "mcap": "Large"},
    "KOTAKBANK": {"name": "Kotak Mahindra Bank", "sector": "Financials", "mcap": "Large"},
    "AXISBANK": {"name": "Axis Bank", "sector": "Financials", "mcap": "Large"},
    "TATAMOTORS": {"name": "Tata Motors", "sector": "Automobile", "mcap": "Large"},
    "TATASTEEL": {"name": "Tata Steel", "sector": "Materials", "mcap": "Large"},
    "WIPRO": {"name": "Wipro", "sector": "Information Technology", "mcap": "Large"},
    "HCLTECH": {"name": "HCL Technologies", "sector": "Information Technology", "mcap": "Large"},
    "POWERGRID": {"name": "Power Grid Corporation", "sector": "Utilities", "mcap": "Large"},
    "NTPC": {"name": "NTPC", "sector": "Utilities", "mcap": "Large"},
    "ONGC": {"name": "Oil & Natural Gas Corp", "sector": "Energy", "mcap": "Large"},
    "COALINDIA": {"name": "Coal India", "sector": "Energy", "mcap": "Large"},
    "ADANIENT": {"name": "Adani Enterprises", "sector": "Conglomerate", "mcap": "Large"},
    "ADANIPORTS": {"name": "Adani Ports", "sector": "Industrials", "mcap": "Large"},
    "JSWSTEEL": {"name": "JSW Steel", "sector": "Materials", "mcap": "Large"},
    "TECHM": {"name": "Tech Mahindra", "sector": "Information Technology", "mcap": "Mid"},
    "DIVISLAB": {"name": "Divi's Laboratories", "sector": "Healthcare", "mcap": "Large"},
    "CIPLA": {"name": "Cipla", "sector": "Healthcare", "mcap": "Large"},
    "DRREDDY": {"name": "Dr. Reddy's Laboratories", "sector": "Healthcare", "mcap": "Large"},
    "EICHERMOT": {"name": "Eicher Motors", "sector": "Automobile", "mcap": "Large"},
    "M&M": {"name": "Mahindra & Mahindra", "sector": "Automobile", "mcap": "Large"},
    "HEROMOTOCO": {"name": "Hero MotoCorp", "sector": "Automobile", "mcap": "Mid"},
    "BRITANNIA": {"name": "Britannia Industries", "sector": "FMCG", "mcap": "Large"},
    "DABUR": {"name": "Dabur India", "sector": "FMCG", "mcap": "Mid"},
    "PIDILITIND": {"name": "Pidilite Industries", "sector": "Materials", "mcap": "Mid"},
    "HAVELLS": {"name": "Havells India", "sector": "Industrials", "mcap": "Mid"},
    "DIXON": {"name": "Dixon Technologies", "sector": "Information Technology", "mcap": "Mid"},
    "POLYCAB": {"name": "Polycab India", "sector": "Industrials", "mcap": "Mid"},
    "PERSISTENT": {"name": "Persistent Systems", "sector": "Information Technology", "mcap": "Mid"},
    "COFORGE": {"name": "Coforge", "sector": "Information Technology", "mcap": "Mid"},
    "IRCTC": {"name": "IRCTC", "sector": "Consumer Discretionary", "mcap": "Mid"},
    "ZOMATO": {"name": "Eternal (Zomato)", "sector": "Consumer Discretionary", "mcap": "Large"},
    "PAYTM": {"name": "One 97 Communications", "sector": "Financials", "mcap": "Mid"},
    "NYKAA": {"name": "FSN E-Commerce (Nykaa)", "sector": "Consumer Discretionary", "mcap": "Mid"},
    "DMART": {"name": "Avenue Supermarts", "sector": "Consumer Discretionary", "mcap": "Large"},
    "TRENT": {"name": "Trent", "sector": "Consumer Discretionary", "mcap": "Large"},
    "PIDILITE": {"name": "Pidilite Industries", "sector": "Materials", "mcap": "Mid"},
    "LTIM": {"name": "LTIMindtree", "sector": "Information Technology", "mcap": "Large"},
    "SBILIFE": {"name": "SBI Life Insurance", "sector": "Financials", "mcap": "Large"},
    "HDFCLIFE": {"name": "HDFC Life Insurance", "sector": "Financials", "mcap": "Large"},
    "BAJAJHLDNG": {"name": "Bajaj Holdings", "sector": "Financials", "mcap": "Large"},
    "GRASIM": {"name": "Grasim Industries", "sector": "Materials", "mcap": "Large"},
    "HINDALCO": {"name": "Hindalco Industries", "sector": "Materials", "mcap": "Large"},
    "BPCL": {"name": "Bharat Petroleum", "sector": "Energy", "mcap": "Large"},
    "IOC": {"name": "Indian Oil Corporation", "sector": "Energy", "mcap": "Large"},
    "INDIGO": {"name": "InterGlobe Aviation", "sector": "Industrials", "mcap": "Large"},
    "VEDL": {"name": "Vedanta", "sector": "Materials", "mcap": "Large"},
}


def enrich(symbol: str, company_name: str | None = None, sector: str | None = None) -> dict[str, str]:
    meta = UNIVERSE.get(symbol.upper(), {})
    return {
        "name": company_name or meta.get("name") or symbol,
        "sector": sector or meta.get("sector") or "Unclassified",
        "mcap": meta.get("mcap") or "Unclassified",
    }
